### ISSUE TITLE
Project (2021-03 Plugfest): RIOT OS implementation

### ISSUE THREAD

**Issue by Citrullin** [w3c/wot-testing#105]
The purpose of this test is to figure out potential issues with the WoT TD server implementation in [RIOT OS](http://riot-os.org/). IPv6 addresses are [shared on the slack](https://wotpf.slack.com/archives/C01561VADQV/p1614582685004600).

How to for flashing the ESP32:
The [working branch is wot_coap](https://github.com/Citrullin/RIOT/tree/wot_gcoap).
wot_coap_light_switch contains some [helper scripts to install the ESP32 toolchain and dependencies](https://github.com/Citrullin/RIOT/tree/wot_gcoap/tests/wot_coap_light_switch). 
- Use install_esp_toolchain.sh to install the ESP toolchain.
- Use install_esp_dependencies.sh to install the ESP dependencies
- Move into [wot_coap_generation directory](https://github.com/Citrullin/RIOT/tree/wot_gcoap/tests/wot_coap_generation)
- Change the WiFi setting in the Makefile.
- Compile the app with ```./compile_esp_app.sh```
- Flash it with: ```./flash_esp_app.sh```
- You can connect to the RIOT shell with ```APPLICATION=wot_test BOARD=esp32-wroom-32 make term``` after it successfuly flashed.
- Get the IPv6 with ```ifconfig``` on the RIOT shell.

Findings:
- Fix for IPv6 in node-wot [still has some issues](https://github.com/eclipse/thingweb.node-wot/issues/363). 
- ESP32s don't get IPv6 addresses all the time. They need to get rebooted a couple of times before they get one.
- Over the night most of the ESP32s completly died and weren't accessible over CoAP or via ping. The ones who were accessible had a very high ping. 
- ESP32s have a very unstable WiFi connection.
- TD response isn't always correct on the first try, but when repeating the request you get often the correct response.

**Comment by JKRhb** [comment]
In our RIOT OS implementation, we already support the use of a TM (in combination with instance specific information) as input for creating the C config code. Our parser, however, does not yet support the newly introduced `extend` mechanism which is an aspect I will try to work on this week.
