### ISSUE TITLE
Project (2021-03): Create OneDM/SDF Semantic Annotation Examples

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#108]
Description:
* Update examples (don't have to be live devices) that use semantic annotations derived from SDF and OneDM.
* These would also be useful test cases for semantic search in directories using SPARQL.

Participants
* Michael Koster
* Michael McCool

To Do:
- [x] Create examples that use SDF annotations (see [MODBUS example](link))
- [ ] Propose updates to TD to allow objects for @type to allow contentType for URIs (see/comment on fragment identifier issues)
- [ ] Validate (if possible)
- [ ] Create PR to push into wot-testing repo
- [ ] Register examples with WoT TD Directory (can be sourced from wot-testing)
- [ ] Prototype some use cases (e.g. SPARQL (or JSON path?) query for all temp sensors)

**Comment by mjkoster** [comment]
Here are the examples from before:
https://github.com/mjkoster/ODM-Examples/blob/master/switch.sdf.json
https://github.com/mjkoster/ODM-Examples/blob/master/switch-td.json

**Comment by mjkoster** [comment]
Here are the SDF Thing examples I'm working with to create TDs from for this week:
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/sdfthing-modbus-dcpowersupply.sdf.json
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/sdfthing-modbus-ehd-rtu.sdf.json

And slides to explain things:
https://github.com/mjkoster/onefb-sdk/blob/main/documents/onedm-plughackthonfest.pdf

**Comment by mjkoster** [comment]
Here is a new TD for the modbus project:
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/modbus-rtu.td.jsonld
And here is the SDF source file with extensions to generate the TD:
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/sdfthing-modbus-ehd-rtu.sdf.json

**Comment by mjkoster** [comment]
There is a local node-red application for reference:
http://10.0.0.207:1880/#flow/590c69.67079398
And an example node-red dashboard:
http://71.202.145.92:1880/ui

**Comment by mjkoster** [comment]
Please review the "@type" and "links" annotation in the modbus TD. I expanded the URIs, until we figure out how to consume compact URIs according to a contentType. I also annotated the content type in the @type statements using RDF construction. Will this work for TD? 
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/modbus-rtu.td.jsonld
