### ISSUE TITLE
Project (2021-03 Plugfest): Node-RED integration

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-testing#112]
Description:
- Directory-based discovery and auto-population (in addition to existing mDNS discovery)
- (stretch goal) use CoRE-RD instance on IETF Hackathon
- (stretch goal) keyword-based filtering of results (using JSON Path queries, UI just has keywords to filter on)

Participant:
- Kunihiko Toumura (@k-toumura )

Links:
- Description in past Plugfest:
  - [2020.06](https://github.com/w3c/wot-testing/blob/main/events/2020.06.Online/prototypes/nodepop.md),
  - [2020.09](https://github.com/w3c/wot-testing/blob/main/events/2020.09.Online/prototypes/Hitachi/README.md)

Activities:
- [x] Fix bugs in Node Generator, e.g. IPv6 address handling, CoAP binding, etc.
- [x] Check availability of Things and Directories
- [x] Create UI for querying Directory from Node-RED

**Comment by mmccool** [comment]
Please contact @farshidtz for information on LinkSmart directory service access - it is up.

**Comment by farshidtz** [comment]
I had provided the access details on Slack.

The directory is public and populated with event TDs inside this repo. 

Please find the details here:
https://demo.linksmart.eu/thing-directory/

Keep in mind that the API is not fully inline with the latest draft spec.

The directory population happens every hour now, but I'll change to nightly from next week. It is based on https://github.com/w3c/wot-testing/tree/main/events/2020.06.Online/tools/directory-sync

**Comment by mmccool** [comment]
@mjkoster mentioned a Node-RED example using Modbus nodes... see link.
