### ISSUE TITLE
Project (2021-09 Plugfest): Node-RED integration (SPARQL query)

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-testing#154]
Description:
- Directory-based discovery (using SPARQL) and auto-population

Participant:
- Kunihiko Toumura (@k-toumura)

Activities:
- [x] Check availability of Things and Directories
- [x] Create UI for querying Directory from Node-RED
- [x]  Test auto-population feature using participating Things

Current implementation uses following simple SPARQL query:
```sparql
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?id ?title ?desc
WHERE {
    ?id rdf:type td:Thing;
        dc:title ?title;
        dc:description ?desc.
    FILTER(contains(?desc, "${query}")).
}
LIMIT 100
```
(`${query}` = input from Node-RED search UI)

**Comment by k-toumura** [comment]
Draft result report is [here](https://github.com/k-toumura/document-for-wot/blob/master/2021-10-01-nodered-directory-ktoumura.pdf).

**Comment by FadySalama** [comment]
Migrated to MD file in PR #202
