### ISSUE TITLE
Project (2021-09 Plugfest): Geolocation - Intel

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#167]
Description:
- Ontology for embedding geolocation data in TDs and in Thing
- Example TDs and services
- Geolocation filters in SPARQL
- See Intel TDs and Project

**Comment by mmccool** [comment]
Observations:
- Need way to distinguish fetching data from a TD itself vs. from an interaction the TD describes
- Problem may also be more general and apply to other kinds of data, e.g. temperature
- May also be other kinds of data that is static vs dynamic, and described by separate thing
- Need to think about JSON pointer syntax related to TD fragment identifier (IANA registered, assuming)

**Comment by FadySalama** [comment]
Migrated to MD file in PR #202
