### ISSUE TITLE
Project (2021-09 Plugfest): SDF Conversion

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#183]
See PR https://github.com/w3c/wot-testing/pull/177
- would be useful to have a link back to the source data (a general issue when one thing is generated from another) and also to name the corresponding sdf model
- not clear how exactly to map sdfObjects to TM modularity; currently flattening
- accelerometer is a possible candidate for a geolocator; can it be annotated with the proposed geolocation ontology?
- some issues as well with vector values being provided component by component.  Are these measured at the same time, or different time?  Are they registered, and if so, should there be an action to trigger a "reading"?
- schemas that can group elements of a vector (or label them) would be useful

**Comment by FadySalama** [comment]
Migrated to MD file in PR #202
