### ISSUE TITLE
Project (2021-09 Plugfest): Shadow Proxy - Fujitsu

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#184]
see https://github.com/w3c/wot-testing/pull/181

**Comment by mryuichi** [comment]
The presentation slide is [pdf](https://github.com/mryuichi/documents/blob/master/Fujitsu-plugfest-TPAC2021.pdf) and [ppt](https://github.com/mryuichi/documents/blob/master/Fujitsu-plugfest-TPAC2021.pptx).

**Comment by FadySalama** [comment]
Migrated to MD file in PR #202
