### ISSUE TITLE
Project (2021-09 Plugfest): TM Composition

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-testing#194]
The [PR](https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1207.html#thing-model-composition) introduces a new feature about Thing Model composition.

During PlugFest, [examples](https://github.com/w3c/wot-testing/tree/main/events/2021.09.Online/TD/TMs/Siemens) were created to gain experience with this modeling concept and to generate TD instances.  

During the vF2F Thing Description session, a short [presentation](https://github.com/w3c/wot/blob/main/PRESENTATIONS/2021-10-online-f2f/2021-10-07-WoT-F2F-TD-Kaebisch.pdf) was provided (slide 7). 

Result:
- so far, the composition feature works quite smoothly
- maybe we can rethink about alternative names for "instanceName"

Next steps:
- composition should be also supported by the ediTDor tool

**Comment by FadySalama** [comment]
migrated to md file in PR #202
