### ISSUE TITLE
Implementation Description should be separated from Testimonial

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-testing#254]
We have changed the implementation report to be  based on the implementations rather than the companies. However, the implementation description seems to be heavily oriented for companies since it is expected to provide:
- Testimonial: A testimonial should be from a company, not from an implementation. A company can be supporting and developing an implementation
- Multiple Implementations: There are different `div`s for different implementations of a company. There should be only one no?

**Comment by mmccool** [comment]
Yeah, I think that is a good idea.  For example, Eclipse has node-wot, but won't give a testimonial.
Let me reorganize it and have two templates.

**Comment by mmccool** [comment]
I'll create new templates and check them in under new names, then update the Intel implementation descriptions and testimonials to factor things out, but won't touch other files and won't check in the PR.  Then we can discuss tomorrow.

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-testing/pull/256

**Comment by egekorkan** [comment]
@mmccool I hope you did not start working on this already, please see https://github.com/w3c/wot-testing/pull/258
