### ISSUE TITLE
Adding dart_wot to implementations

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-testing#307]
I have just realized that dart_wot by @JKRhb is not in the list of implementations. It is already public at https://pub.dev/packages/dart_wot and if @JKRhb agrees to, it would be nice to have it as a consumer implementation. This would mean writing an implementation description and filling the manual.csv for only the consumer related parts

**Comment by JKRhb** [comment]
> and if @JKRhb agrees to, it would be nice to have it as a consumer implementation.

Sure, would be great to have it in the list :)

> This would mean writing an implementation description and filling the manual.csv for only the consumer related parts

Shall I open a PR like https://github.com/w3c/wot-testing/pull/300/files for that? I guess the files will go into this folder, right? https://github.com/w3c/wot-testing/tree/main/events/2022.06.Online

**Comment by egekorkan** [comment]
Yes, more or less. You can also start by doing the implementation description since that should not change. The manual csv might change again in the coming weeks until the CR transition of the TD.
