### ISSUE TITLE
Missing TD Features

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-testing#327]
Currently the gaps we see in the implementation report are:

- [ ] unobserveproperty op value
- [ ] queryaction op value
- [ ] cancelaction op value
- [ ] contentMediaType
- [ ] contentEncoding
- [ ] exclusiveMinimum
- [ ] exclusiveMaximum
- [ ] minLength
- [ ] multipleOf
- [ ] pattern
- [ ] `@type` in security definitions
- [ ] device flow in OAuth2
- [ ] synchronous in actions
- [ ] 1 more cancellation and subscription
- [ ] extensions to bearer format and alg
- [ ] combo scheme
- [ ] anchor 
- [ ] `in` in Digest
- [ ] `name` in Basic and Digest Security Scheme
- [ ] 1 more for combo
- [ ] proxy in security
- [ ] qop in Digest
- [ ] icon and sizes

I will update this issue with newly identified gaps

**Comment by mmccool** [comment]
Let's just look at the actual report and see what the gaps are that way.  Otherwise they are too hard to keep updated.
