### ISSUE TITLE
TM testing

### ISSUE THREAD

**Issue by relu91** [w3c/wot-testing#358]
I've noticed a couple of todos for TMs in the https://github.com/w3c/wot-thing-description/blob/main/testing/todo.csv. However, I'm not sure where to place some samples of TMs under https://github.com/w3c/wot-testing/tree/main/events/2022.06.Online. Is there some specific folder or is ok to place those under TD?

**Comment by egekorkan** [comment]
You should put them under TD and under your specific implementation.

**Comment by mmccool** [comment]
However, please put new data under data/input_2022 as described in the README.  Apparently resolved tho, so we will close.
