### ISSUE TITLE
Uncounted data schema terms

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-testing#360]
There is a TD with many data schema features but it seems that they are not counted: https://github.com/w3c/wot-testing/blob/main/events/2022.06.Online/TD/node-wot/TDs/siemens-dataSchemas.jsonld

We should find out where the problem lies but I guess something to do with playground

**Comment by egekorkan** [comment]
@mmccool please rerun your tools. I have fixed one small bug about `multipleOf` but it does not explain the lack of keywords like `pattern` . So, I hope that running your tools again fixes this. When I use the web version of playground, I get `pattern` as implemented for the above-linked TD

**Comment by mmccool** [comment]
rerun redone!

**Comment by egekorkan** [comment]
Fixed!
