### ISSUE TITLE
Errors in Batch Validation

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#376]
Some issues with the data in data/input_2022:
- [x] Some Ditto TDs have duplicate IDs and Titles
- [x] Non-JSONLD files, e.g. ttl files in ECLASS, md elsewhere (should be removed)
- [x] JSON Pointer issues (in ECLASS - Siemens SENTRON PAC2200971?)
- [x] SortingLineWithDetector2Layer2539 - currentPosition 
- [x] TinyIoT - incorrect context
- [x] Duplicate ID/title in sdf-wot-convertor, but seems to be related to TDs with neither an id or title, since both are optional, and if you have two such files, you also have a "duplicate"

Also it seems TMs are not getting checked on checkin.  Also would be nice if assertionTester could report a filename on an error (title and id are not enough since may not be present...)

**Comment by egekorkan** [comment]
@mmccool the last task is also done thanks to https://github.com/thingweb/thingweb-playground/pull/318 . Please rerun your tool and close the issue, hopefully :)

**Comment by egekorkan** [comment]
This was fixed given that generation worked in last testfest call
