### ISSUE TITLE
Wrong tm:ref usage in sdf wot converter

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-testing#514]
@JKRhb your usage of `tm:ref` is not being picked up by the assertion tester since you are not putting the URL in the beginning. The TD spec says:

> The tm:ref value MUST follow the pattern
> 
>     - file location as URI [[RFC3986](https://w3c.github.io/wot-thing-description/#bib-rfc3986)](Section 4.1)), followed by
>     - # character, and followed by
>     - JSON Pointer [[RFC6901](https://w3c.github.io/wot-thing-description/#bib-rfc6901)] definition.

You are using

`"tm:ref": "#/schemaDefinitions/sdfObject~1GenericLevel~1sdfData~1GenericLevelData"`

So it does not match the correct pattern that is used for checking the usage of tm:ref. Could you update your TMs so that they point to the file first, then # and the location in the file?

**Comment by JKRhb** [comment]
Thank you for the feedback, @egekorkan! In this case, however, the `tm:ref` should be a relative JSON pointer, referring to the same document, so the URI part should be assumed empty (also see the paragraph following these bullet points). Therefore, I am not sure if the TMs or the assertion tester should be adjusted here?

**Comment by egekorkan** [comment]
So from the TD spec, I read it as if the URL should not be empty but it is of course a bit vague on this point. I can also change the regex in general inside assertion testing. I use 
`
    "tm_ref": {
      "type": "string",
      "pattern": "^([a-zA-Z][a-zA-Z0-9+\\-.]*:[^\\s]*)(#(?:/(?:[a-zA-Z0-9_\\-.!$&'()*+,;:=@]|%[0-9a-f]{2}|~0|~1)*)*)$"
    }
` 
and the the spec's schema simply  `uri-reference`

**Comment by JKRhb** [comment]
> So from the TD spec, I read it as if the URL should not be empty but it is of course a bit vague on this point. 

Hmm, what I was referring to were these two sentences:

> Note that the URI can also be empty, indicating a same-document reference [[RFC3986](https://w3c.github.io/wot-thing-description/#bib-rfc3986)](Section 4.4)). In this case, the tm:ref is supposed to be interpreted as a relative reference.

So from my understanding, the JSON pointer with no leading URI (or rather: an empty one) should be fine. I remember, however, that we had some discussion in this regard, and I am not sure how we resolved it. I think there was some discussion regarding the use of the leading `#`?

> I can also change the regex in general inside assertion testing. I use `"tm_ref": { "type": "string", "pattern": "^([a-zA-Z][a-zA-Z0-9+\\-.]*:[^\\s]*)(#(?:/(?:[a-zA-Z0-9_\\-.!$&'()*+,;:=@]|%[0-9a-f]{2}|~0|~1)*)*)$" }` and the the spec's schema simply `uri-reference`

Oh, that would be great! (If my approach is valid, of course.)

**Comment by egekorkan** [comment]
>  Hmm, what I was referring to were these two sentences:

Ah I overlooked this, I will fix assertion tester. Closing
