### ISSUE TITLE
Experiment with visualization in Maps

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#76]
- drive geolocation requirements and test
- Google Maps, OpenStreet Maps

**Comment by danielpeintner** [comment]
I did create a very simple mockup for TDs on a map (see https://github.com/w3c/wot-testing/tree/master/events/2020.09.Online/TDs/Siemens#geolocation-of-wot-things-mockup)

Note: somehow the htmlpreview service does not work with it (I can present it from my machine).

Nevertheless I would like to bring up some aspects I think are important...

### What do we want to show on the map ?
* of course the location
  * Difficulties: I found 3 different ways the location is conveyed (in `events/2020.09.Online`)
    * `"s:longitude": "35.70352", "s:latitude": "139.4720174"`
    * `"geo":{"latitude":"44.513348", "longitude":"11.3193218"}`
    * `"position": {"x": 11.703963279724121, "y": -19.781078338623047, "z": 9.677474021911621}`
* Where to find the ThingDescription
  * is not part of the TD!
  * what is the best way to indicate/transmit it anyway
* Is there a user interface one can use (or point to)
  * e.g., http://plugfest.thingweb.io/examples/smart-coffee-machine.html or http://plugfest.thingweb.io/examples/counter.html
  * again not part of a TD!
* What else ?
  * current property values (difficult when it comes to protected things) --> better a dedicated UI?
  * ...

**Comment by mmccool** [comment]
Will leave open for now as it's relevant to our discussion with OGC, Spatial Data on the Web IG, etc.
