### ISSUE TITLE
Catalogue Major Accomplishment from 2020.09-10 Plugfest

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-testing#92]
* NHK Hybridcast of coffee (incl. TUM/Siemens mashup)
* Node-red/discovery integration (incl. NHK mashup)
* Farm/TUM mashup: display sprinkler status
* Geospatial prototyping and map visualization

**Comment by relu91** [comment]
> - Farm/TUM mashup: display sprinkler status

FYI: I updated [mashup folder](https://github.com/w3c/wot-testing/tree/master/events/2020.09.Online/scenarios/farm) with slides and a [video](https://youtu.be/JqKBwkvrjio).

**Comment by relu91** [comment]
Just noticed this cool feature of Github. Here you have also a screenshot taken from the video. It shows the synchronization between the Farm and TUM. ![plugfest_outcome](https://user-images.githubusercontent.com/3170227/96897372-cfd9c880-148e-11eb-8ec4-015aa4aedb0f.png)

**Comment by mmccool** [comment]
Breakout slides now at https://www.w3.org/2020/10/27-wot-breakout/ 
Note these are too big to put on github.  I do have one update from Cristiano (a shorter version of his video) that I've embedded in the deck for the breakout but have not yet had a chance to upload.  I'll do that between the first and second breakout session.
